name: GuiShop
main: GuiShop\Main
version: 1.0.0-BETA2
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: VMPE Developement Team
description: ShopUI for servers!
commands:
 shop:
  description: Opens a shop UI
